version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NETWORK_NAME=${NETWORK_NAME}
    # Required for network scanning capabilities
    network_mode: host
    # volumes:
    #   # Mount for logs (optional)
    #   - ./logs:/app/logs
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Agent is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.25'
